defaults:
  - pipeline: gaussian_discriminator_pipeline.yaml
  - dataset: nuscene_novel_view.yaml

seed: 42
mode: train

checkpointing:
  every_n_train_steps: 1000
  save_top_k: 1
  save_weights_only: False

trainer:
  max_steps: 100000
  num_nodes: 1
  devices: 1
  val_check_interval: 1.0

data_module:
  train:
    num_workers: 4
    persistent_workers: true
    batch_size: 4
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1